#!/usr/bin/env bash
# Webservers are used to serve web pages and applications. 
# Nginx is a popular web server that is used to serve web pages and applications. 
# Listens on port 80 by default.
# https://www.nginx.com/
# Returns the page containing "Hello World!" when accessed.
# at the root with a curl GET request.
# Lets go ahead and install Nginx.

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'