#!/usr/bin/bin/env bash
# Configure Nginx so that /redirect_me is redirected to another page.
# The redirection must be a "301 Moved Permanently".


sudo apt-get update
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World" > /var/www/html/index.nginx-debian.html'
sudo sed -i 'listen 80 default_server/a rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart