#!/usr/bin/bin/env bash
# Configure Nginx so that /redirect_me is redirected to another page.
# The redirection must be a "301 Moved Permanently".


sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER:$USER" /var/ww/html
sudo Chown -R "$USER:$USER" /etc/nginx/sites-available

touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart