#!/usr/bin/env bash
# Configure Nginx server to have 404 page that contains the string "Ceci n'est pas une page".
# Page returns an HTTP status code 404.
# The page must contain 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu server.


sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/ww/html
sudo Chown -R "$USER":$"USER" /etc/nginx/sites-available/default 

touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html

touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart