#!/usr/bin/env bash
# This script pings an IP Address passed as an argument 5 times

if [ -z "$1" ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

if ! [[ $1 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echo "Invalid IP Address format. Please provide a valid IP Address."
    exit 1

ping -c 5 "$1"