#!/usr/bin/env bash
# Install firewall and block all incoming traffic but allow outgoing traffic

sudo agt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing 
sudo ufw allow 22/tcp # allow SSH
sudo ufw allow 443/tcp # allow HTTPS SSL
sudo ufw allow 80/tcp # allow HTTP
sudo ufw enable